In [2]:
import torch
import torch.nn as nn

**Saving complete model**
1. `torch.save(model, PATH)`
2. `model = torch.load(PATH)`
3. `model.eval()`

In [4]:
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)
    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

In [6]:
FILE = "backup/model.pth"

model = Model(n_input_features=6)
torch.save(model, FILE)

In [7]:
model = torch.load(FILE)
model.eval()

for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.1494,  0.0961, -0.1926,  0.0182, -0.3812, -0.2548]],
       requires_grad=True)
Parameter containing:
tensor([0.0770], requires_grad=True)


**Saving state dict**
1. `torch.save(model.state_dict(), PATH)`
2. `model = Model(*arg, **kargs)`
3. `model.load_state_dict(torch.load(PATH))`
4. `model.eval()`

In [8]:
FILE = "backup/model_state_dict"

torch.save(model.state_dict(), FILE)

In [9]:
model2 = Model(n_input_features=6)
model2.load_state_dict(torch.load(FILE))
model2.eval()
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.1494,  0.0961, -0.1926,  0.0182, -0.3812, -0.2548]],
       requires_grad=True)
Parameter containing:
tensor([0.0770], requires_grad=True)


In [11]:
# saving checkpoints

optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

checkpoint = {
    'epoch' : 90,
    "model_state" : model.state_dict(),
    'optim_sate' : optimizer.state_dict()
}
torch.save(checkpoint, 'backup/checkpoint.pth')

In [14]:
loaded_checkpoint = torch.load('backup/checkpoint.pth')
epoch = loaded_checkpoint['epoch']
model = Model(n_input_features=6)
optimizer = torch.optim.SGD(model.parameters(), lr=0.00001)
model.load_state_dict(checkpoint['model_state'])
optimizer.load_state_dict(checkpoint['optim_sate'])
print(model.state_dict())

OrderedDict([('linear.weight', tensor([[ 0.1494,  0.0961, -0.1926,  0.0182, -0.3812, -0.2548]])), ('linear.bias', tensor([0.0770]))])


In [ ]:
# GPU to CPU

decive = torch.device('cuda')
model.to(device)
torch.save(model.state_dict(), PATH)

device = torch.device('cpu')
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location=device))

In [ ]:
# CPU to GPU

torch.save(model.state_dict(), PATH)

device = torch.device('cuda')
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location='cuda:0'))
model.to(device)