In [1]:
import torch
import torch.nn as nn

In [30]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.1243,  1.0740,  0.9862], requires_grad=True)


In [31]:
y = torch.sin(x)**2
print(y)

tensor([0.0154, 0.7728, 0.6955], grad_fn=<PowBackward0>)


In [32]:
y = torch.mean(y)
y.backward()
print(x.grad)

tensor([-0.0820,  0.2793,  0.3068])


In [29]:
# # stop grad tracking 1
# x.requires_grad_(False)
# print(x)

# # stop grad tracking 2
# y = x.detach()

# # stop grad tracking 3
# with torch.no_grad():

# # grad 초기화
# x.grad.zero_()

# optimizer = torch.optim.SGD(weights, lr = 0.001)
# optimizer.step()
# optimizer.zero_grad()

In [19]:
# linear regression

X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([3, 5, 7, 9], dtype=torch.float32)

w = torch.tensor(0, dtype=torch.float32, requires_grad=True)
b = torch.tensor(0, dtype=torch.float32, requires_grad=True)

def forward(x):
    return w*x +b

def loss(y_pred, y_train):
    return ((y_pred - y_train)**2).mean()

lr = 0.1
n_iters = 100

for epoch in xrange(n_iters):
    y_pred = forward(X)
    l = loss(y_pred, y)
    l.backward()
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
    w.grad.zero_()
    b.grad.zero_()
    if epoch%10 -1 == 0:
        print("epoch %d : w = %.3f, b = %.3f, loss = %.3f"%(epoch+1, w.item(), b.item(), l.item()))
print("prediction for f(5) : %.3f"%(forward(5)))


epoch 2 : w = 1.150, b = 0.410, loss = 18.415
epoch 12 : w = 2.051, b = 0.795, loss = 0.013
epoch 22 : w = 2.050, b = 0.853, loss = 0.004
epoch 32 : w = 2.037, b = 0.892, loss = 0.002
epoch 42 : w = 2.027, b = 0.920, loss = 0.001
epoch 52 : w = 2.020, b = 0.941, loss = 0.001
epoch 62 : w = 2.015, b = 0.956, loss = 0.000
epoch 72 : w = 2.011, b = 0.968, loss = 0.000
epoch 82 : w = 2.008, b = 0.976, loss = 0.000
epoch 92 : w = 2.006, b = 0.983, loss = 0.000
prediction for f(5) : 11.010


In [7]:
# linear regression

X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
y = torch.tensor([[3], [5], [7], [9]], dtype=torch.float32)

X_test = torch.tensor([[5]], dtype=torch.float32)

number_of_samples, number_of_features = X.shape
print(number_of_samples, number_of_features)

input_size = number_of_features
output_size = number_of_features

model = nn.Linear(input_size, output_size)

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
n_iters = 1000

for epoch in xrange(n_iters):
    y_pred = model(X)
    l = loss(y_pred, y)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
    if (epoch+1)%100 == 0:
        w, b = model.parameters()
        print("epoch %d : w = %.3f, b = %.3f, loss = %.3f"%(epoch+1, w, b, l))
print("prediction for f(5) : %.3f"%(forward(X_test)))

(4, 1)
epoch 100 : w = 1.958, b = 1.123, loss = 0.003
epoch 200 : w = 1.969, b = 1.091, loss = 0.001
epoch 300 : w = 1.977, b = 1.068, loss = 0.001
epoch 400 : w = 1.983, b = 1.050, loss = 0.000
epoch 500 : w = 1.987, b = 1.037, loss = 0.000
epoch 600 : w = 1.991, b = 1.027, loss = 0.000
epoch 700 : w = 1.993, b = 1.020, loss = 0.000
epoch 800 : w = 1.995, b = 1.015, loss = 0.000
epoch 900 : w = 1.996, b = 1.011, loss = 0.000
epoch 1000 : w = 1.997, b = 1.008, loss = 0.000
prediction for f(5) : 10.994


1. Make Model (using torch.nn)
2. Make Loss (using torch.nn)
3. Make Optimizer (using torch.optim)
4. Train loop (lr and n_iter)
    * forward pass : model(X)
    * backward pass : loss.backward()
    * update parameters : optimizer.step()
    * reset grad : optimizer.grad_zero()

In [8]:
## OOP

class MyModel(nn.Module):

    def __init__(self, input_dim, output_dim):
        super(MyModel, self).__init__()
        self.lin = nn.Linear(input_dim, output_dim)

    def forward(self, X):
        return self.lin(X)


X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
y = torch.tensor([[3], [5], [7], [9]], dtype=torch.float32)

X_test = torch.tensor([[5]], dtype=torch.float32)

number_of_samples, number_of_features = X.shape

model = MyModel(input_size, output_size)

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

n_iters = 1000

for epoch in xrange(n_iters):
    y_pred = model(X)
    l = loss(y_pred, y)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
    if (epoch+1)%100 == 0:
        w, b = model.parameters()
        print("epoch %d : w = %.3f, b = %.3f, loss = %.3f"%(epoch+1, w, b, l))
print("prediction for f(5) : %.3f"%(forward(X_test)))


epoch 100 : w = 2.005, b = 0.986, loss = 0.000
epoch 200 : w = 2.003, b = 0.990, loss = 0.000
epoch 300 : w = 2.003, b = 0.993, loss = 0.000
epoch 400 : w = 2.002, b = 0.994, loss = 0.000
epoch 500 : w = 2.001, b = 0.996, loss = 0.000
epoch 600 : w = 2.001, b = 0.997, loss = 0.000
epoch 700 : w = 2.001, b = 0.998, loss = 0.000
epoch 800 : w = 2.001, b = 0.998, loss = 0.000
epoch 900 : w = 2.000, b = 0.999, loss = 0.000
epoch 1000 : w = 2.000, b = 0.999, loss = 0.000
prediction for f(5) : 11.001
